# Generated by Django 4.2.7 on 2023-11-19 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RegistrationForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=15)),
                ('emailid', models.CharField(default='', max_length=100)),
                ('password', models.CharField(default='', max_length=10)),
                ('mobilenumber', models.CharField(default='', max_length=10)),
                ('pincode', models.CharField(default='', max_length=10)),
                ('city', models.CharField(default='', max_length=20)),
            ],
        ),
    ]
