# Generated by Django 4.2.7 on 2023-11-21 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_customer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drivername', models.CharField(default='', max_length=20)),
                ('vehiclename', models.CharField(default='', max_length=20)),
                ('vehicletype', models.CharField(default='', max_length=300)),
                ('modelyear', models.CharField(default='', max_length=10)),
                ('drivingmobilenumber', models.CharField(default='', max_length=10)),
                ('drivinglicencenumber', models.CharField(default='', max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
