# Generated by Django 4.2.7 on 2023-11-21 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_client_delete_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='drivingmobilenumber',
        ),
        migrations.AddField(
            model_name='client',
            name='city',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='client',
            name='drivermobilenumber',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='client',
            name='rateperkilometer',
            field=models.CharField(default='', max_length=10),
        ),
    ]
