# Generated by Django 4.2.7 on 2024-07-12 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_remove_client_drivingmobilenumber_client_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='emailid',
            field=models.CharField(default='', max_length=100),
        ),
    ]
