# Generated by Django 4.2.7 on 2025-03-03 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employeeid', models.CharField(max_length=100)),
                ('fullname', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=100)),
                ('dateofbirth', models.CharField(max_length=13)),
                ('contactnumber', models.CharField(max_length=100)),
                ('emailid', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('softdelete', models.IntegerField(default=0)),
                ('createdon', models.CharField(max_length=100)),
                ('deletedon', models.CharField(default='', max_length=100)),
            ],
        ),
    ]
